name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

  who-to-greet-2: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  random-number:
    description: "Random number"
    value: "Random"

#runs:
#  using: 'docker'
#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.who-to-greet }}

runs:
  using: "composite"
  steps:
    - run: |
        pwd
        ls -la
      shell: bash
    - shell: bash
      env:
        TEST: "TEST ENV"
      run: ${{ github.action_path }}/entrypoint.sh
