on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: kingbj940429/hello-world-composite-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: |
          echo $GITHUB_OUTPUT
          echo $RANDOM
          echo $GITHUB_PATH
          echo $INPUT_TAG_VALUE
        shell: bash


#name: Actions WorkFlow
#
#on:
#  pull_request:
#    branch: [ dev ]
#    types: [ closed, assigned, opened, reopened ]
#
#jobs:
#  run-github-actions:
#    runs-on: ubuntu-latest
#    steps:
#      - name: test env
#        if: !contains(github.event.action, 'closed')
#        run: |
#          env
#          echo '${{ toJSON(github) }}'
#      - name: github contexts
#        if: contains(github.event.action, 'closed')
#        run: |
#          echo ${{ github.event.action }}
#          echo '${{ toJSON(github) }}'
#
