name: Actions WorkFlow

on: 
  repository_dispatch:
    types: [build]
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload }}