on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: ./.github/actions/hello-docker
        with:
          who-to-greet: 'Mona the Octocat'
