name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services: # docker compose 처럼 사용할 수 있다
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps: # 얘는 컨테이너가 아닌 가상 환경에서 실행된다
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user"
      - name: Get Users
        run: curl -X GET http://localhost:3001/api/user"