name: shell commands

on: [push] # 여러개라면 배열 가능

jobs:
  run-shell-command: # job name
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v