name: Reusable workflow example

on:
  workflow_call:
    inputs:
      hello:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: reusable test
        env:
          HELLO: ${{ inputs.hello }}
        run: |
          echo "reusable test"
          echo "HELLO: $HELLO"
        
